version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clbhieuvathuong-profile
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Networks
    networks:
      - app-network

networks:
  app-network:
    external: true
