services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clbhieuvathuong-profile
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Mount logs directory for persistence
    volumes:
      - ./logs:/app/logs
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Networks
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
