version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    container_name: clbhieuvathuong-profile
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    # Networks
    networks:
      - app-network

networks:
  app-network:
    external: true
